# Generated by Django 4.2.20 on 2025-03-17 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Appetizer', 'Appetizer'), ('Main Course', 'Main Course'), ('Dessert', 'Dessert'), ('Beverage', 'Beverage')], max_length=20)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('spice_level', models.CharField(choices=[('Mild', 'Mild'), ('Medium', 'Medium'), ('Spicy', 'Spicy'), ('Extra Spicy', 'Extra Spicy')], max_length=20)),
                ('preparation_time', models.PositiveIntegerField(help_text='Estimated time in minutes')),
                ('serving_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuisines', models.ManyToManyField(related_name='menu_items', to='api.restaurantcuisine')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.restaurantmaster')),
            ],
            options={
                'db_table': 'restaurant_menu',
            },
        ),
    ]
