# Generated by Django 4.2.20 on 2025-03-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_cart_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
