class OfferType:
    BOGO = "BOGO"
    DISCOUNT = "DISCOUNT"
    MIN_ORDER_VALUE = "MIN_ORDER_VALUE"
    FREE_DELIVERY = "FREE_DELIVERY"
    TRENDING = "TRENDING"
    NEW = "NEW"
    ALL_OFFER = "ALL_OFFER"